# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec - VSE Win7 Build (onedir, PyQt5 + PaddlePaddle)
Optimized for minimal size
"""
import os
from PyInstaller.utils.hooks import collect_data_files, collect_submodules, collect_all

PROJECT_ROOT = os.path.dirname(os.path.abspath(SPEC))

# Auto-discover ALL stdlib modules for hiddenimports (prevents No module errors)
import pkgutil
_stdlib_names = set()
for finder, modname, ispkg in pkgutil.iter_modules():
    _stdlib_names.add(modname)
    if ispkg:
        # Also add common submodules
        for sub in ['handlers', 'config', 'abc', 'compat', 'util', 'utils',
                     'parse', 'request', 'error', 'response', 'client', 'server',
                     'mime', 'mime.text', 'mime.multipart', 'parser', 'policy',
                     'header', 'iterator', 'message', 'charset', 'encoder',
                     'wintypes', 'metadata', 'resources', 'machinery',
                     'defaultdict', 'ordereddict', 'futures', 'process',
                     'queue', 'reduction', 'connection', 'shared_memory',
                     'managers', 'pool', 'cElementTree', 'minidom', 'pulldom',
                     'parsers.expat', 'sax', 'sax.saxutils', 'sax.handler',
                     'robotparser', 'cookiejar', 'cookies', 'headerregistry',
                     'contentmanager', 'generator', 'encoders']:
            _stdlib_names.add(f'{modname}.{sub}')
_stdlib_hidden = [m for m in sorted(_stdlib_names)
                  if m not in {'test', 'tests', 'tkinter', 'antigravity', 'this'}]


pyqt5_datas, pyqt5_bins, pyqt5_hidden = collect_all('PyQt5')
qfw_datas, qfw_bins, qfw_hidden = collect_all('qfluentwidgets')
qframe_datas, qframe_bins, qframe_hidden = collect_all('PyQt5_Frameless_Window')
paddle_datas, paddle_bins, paddle_hidden = collect_all('paddle')
paddleocr_datas, paddleocr_bins, paddleocr_hidden = collect_all('paddleocr')
pytz_datas, pytz_bins, pytz_hidden = collect_all('pytz')
pydantic_datas, pydantic_bins, pydantic_hidden = collect_all('pydantic')
pydanticcore_datas, pydanticcore_bins, pydanticcore_hidden = collect_all('pydantic_core')
darkdetect_datas, darkdetect_bins, darkdetect_hidden = collect_all('darkdetect')
imageio_ff_datas, imageio_ff_bins, imageio_ff_hidden = collect_all('imageio_ffmpeg')

win7_compat_dir = os.path.join(PROJECT_ROOT, 'win7_compat')
win7_bins = [(os.path.join(win7_compat_dir, f), '.') for f in os.listdir(win7_compat_dir) if f.endswith('.dll')]

added_files = [
    (os.path.join(PROJECT_ROOT, 'backend'), 'backend'),
    (os.path.join(PROJECT_ROOT, 'design'), 'design'),
    (os.path.join(PROJECT_ROOT, 'ui'), 'ui'),
]

all_binaries = (pyqt5_bins + qfw_bins + qframe_bins + paddle_bins + paddleocr_bins
                 + pytz_bins + pydantic_bins + pydanticcore_bins + darkdetect_bins + imageio_ff_bins + win7_bins)
all_datas = (added_files + pyqt5_datas + qfw_datas + qframe_datas + paddle_datas
             + paddleocr_datas + pytz_datas + pydantic_datas + pydanticcore_datas + darkdetect_datas + imageio_ff_datas)

all_hidden = ([
    # Auto-discovered stdlib submodules
    # PaddlePaddle dynamically imports these at runtime
    '4ef79d6367bb14396397__mypyc',
    '81d243bd2c585b0f4821__mypyc',
    'IPython',
    'OleFileIO_PL',
    'PIL',
    '__future__',
    '_abc',
    '_aix_support',
    '_asyncio',
    '_bootsubprocess',
    '_bz2',
    '_cffi_backend',
    '_codecs_cn',
    '_codecs_hk',
    '_codecs_iso2022',
    '_codecs_jp',
    '_codecs_kr',
    '_codecs_tw',
    '_collections_abc',
    '_compat_pickle',
    '_compression',
    '_contextvars',
    '_crypt',
    '_ctypes',
    '_ctypes_test',
    '_curses',
    '_curses_panel',
    '_dbm',
    '_dbus_bindings',
    '_dbus_glib_bindings',
    '_decimal',
    '_distutils_hack',
    '_distutils_system_mod',
    '_functools',
    '_hashlib',
    '_json',
    '_lsprof',
    '_lzma',
    '_markupbase',
    '_multibytecodec',
    '_multiprocessing',
    '_opcode',
    '_osx_support',
    '_posixshmem',
    '_py_abc',
    '_pydecimal',
    '_pyio',
    '_queue',
    '_sitebuiltins',
    '_sqlite3',
    '_ssl',
    '_strptime',
    '_sysconfigdata__linux_x86_64-linux-gnu',
    '_sysconfigdata__x86_64-linux-gnu',
    '_testbuffer',
    '_testcapi',
    '_testclinic',
    '_testimportmultiple',
    '_testinternalcapi',
    '_testmultiphase',
    '_thread',
    '_threading_local',
    '_uuid',
    '_weakrefset',
    '_xxsubinterpreters',
    '_xxtestfuzz',
    '_yaml',
    '_zoneinfo',
    'abc',
    'agate',
    'agatedbf',
    'agateexcel',
    'agatesql',
    'aifc',
    'apt',
    'apt_inst',
    'apt_pkg',
    'aptsources',
    'argparse',
    'ast',
    'asynchat',
    'asyncio',
    'asyncore',
    'atexit',
    'audioop',
    'babel',
    'backcall',
    'base64',
    'bdb',
    'binascii',
    'binhex',
    'bisect',
    'blinker',
    'bs4',
    'bz2',
    'cProfile',
    'calendar',
    'camelot',
    'certifi',
    'cffi',
    'cgi',
    'cgitb',
    'chardet',
    'charset_normalizer',
    'chunk',
    'click',
    'cmath',
    'cmd',
    'code',
    'codecs',
    'codeop',
    'collections',
    'collections.abc',
    'collections.defaultdict',
    'collections.ordereddict',
    'coloredlogs',
    'colorsys',
    'compileall',
    'concurrent',
    'concurrent.futures',
    'concurrent.futures.process',
    'concurrent.futures.thread',
    'configparser',
    'contextlib',
    'contextvars',
    'contourpy',
    'copy',
    'copyreg',
    'crypt',
    'cryptography',
    'csv',
    'csvkit',
    'ctypes',
    'ctypes.util',
    'ctypes.wintypes',
    'curses',
    'cv2',
    'cycler',
    'dataclasses',
    'datetime',
    'dateutil',
    'dbfread',
    'dbm',
    'dbm.dumb',
    'dbus',
    'decimal',
    'decorator',
    'defusedxml',
    'difflib',
    'dis',
    'distro',
    'distutils',
    'doctest',
    'docx',
    'dotenv',
    'email',
    'email.charset',
    'email.contentmanager',
    'email.encoders',
    'email.errors',
    'email.generator',
    'email.header',
    'email.headerregistry',
    'email.iterators',
    'email.message',
    'email.mime',
    'email.mime.base',
    'email.mime.image',
    'email.mime.multipart',
    'email.mime.text',
    'email.parser',
    'email.policy',
    'email.utils',
    'encodings',
    'ensurepip',
    'enum',
    'et_xmlfile',
    'filecmp',
    'fileinput',
    'flatbuffers',
    'fnmatch',
    'fontTools',
    'fractions',
    'ftplib',
    'functools',
    'gc',
    'genericpath',
    'getopt',
    'getpass',
    'gettext',
    'gi',
    'glob',
    'graphlib',
    'greenlet',
    'gzip',
    'hashlib',
    'heapq',
    'hmac',
    'html',
    'http',
    'http.client',
    'http.cookiejar',
    'http.cookies',
    'http.server',
    'httplib2',
    'humanfriendly',
    'idna',
    'imaplib',
    'imghdr',
    'imp',
    'importlib',
    'importlib.abc',
    'importlib.machinery',
    'importlib.metadata',
    'importlib.resources',
    'importlib_metadata',
    'inspect',
    'io',
    'ipaddress',
    'isodate',
    'isympy',
    'itertools',
    'jedi',
    'jeepney',
    'json',
    'jwt',
    'keyring',
    'keyword',
    'kiwisolver',
    'launchpadlib',
    'leather',
    'lib2to3',
    'linecache',
    'locale',
    'logging',
    'logging.config',
    'logging.handlers',
    'lsb_release',
    'lxml',
    'lzma',
    'magika',
    'mailbox',
    'mailcap',
    'markdown',
    'markdownify',
    'markitdown',
    'marshal',
    'math',
    'matplotlib',
    'matplotlib_inline',
    'mimetypes',
    'mmap',
    'modulefinder',
    'more_itertools',
    'mpmath',
    'msvcrt',
    'multiprocessing',
    'multiprocessing.connection',
    'multiprocessing.managers',
    'multiprocessing.pool',
    'multiprocessing.process',
    'multiprocessing.queue',
    'multiprocessing.reduction',
    'multiprocessing.shared_memory',
    'netrc',
    'nis',
    'nntplib',
    'ntpath',
    'nturl2path',
    'numbers',
    'numpy',
    'oauthlib',
    'odf',
    'olefile',
    'onnxruntime',
    'opcode',
    'openpyxl',
    'operator',
    'optparse',
    'os',
    'os.path',
    'ossaudiodev',
    'packaging',
    'pandas',
    'parsedatetime',
    'parso',
    'pathlib',
    'pdb',
    'pdf2image',
    'pdfminer',
    'pdfplumber',
    'pexpect',
    'pickle',
    'pickleshare',
    'pickletools',
    'pip',
    'pipes',
    'pkg_resources',
    'pkgutil',
    'platform',
    'plistlib',
    'poplib',
    'posixpath',
    'pprint',
    'pptx',
    'profile',
    'prompt_toolkit',
    'pstats',
    'pty',
    'ptyprocess',
    'py_compile',
    'pyclbr',
    'pycparser',
    'pydoc',
    'pydoc_data',
    'pygments',
    'pygtkcompat',
    'pylab',
    'pyparsing',
    'pypdf',
    'pypdfium2',
    'pypdfium2_cfg',
    'pypdfium2_cli',
    'pypdfium2_raw',
    'pytesseract',
    'pytimeparse',
    'pytz',
    'queue',
    'quopri',
    'random',
    're',
    'readline',
    'reportlab',
    'reportlab_cjk_autoload',
    'reprlib',
    'requests',
    'resource',
    'rlcompleter',
    'runpy',
    'sched',
    'scipy',
    'seaborn',
    'secrets',
    'secretstorage',
    'select',
    'selectors',
    'setuptools',
    'shelve',
    'shlex',
    'shutil',
    'signal',
    'site',
    'sitecustomize',
    'six',
    'slugify',
    'smtpd',
    'smtplib',
    'sndhdr',
    'socket',
    'socketserver',
    'softwareproperties',
    'soupsieve',
    'sqlalchemy',
    'sqlite3',
    'sre_compile',
    'sre_constants',
    'sre_parse',
    'ssl',
    'stat',
    'statistics',
    'string',
    'stringprep',
    'struct',
    'subprocess',
    'sunau',
    'supervisor',
    'symbol',
    'sympy',
    'symtable',
    'sysconfig',
    'syslog',
    'tabnanny',
    'tabulate',
    'tarfile',
    'telnetlib',
    'tempfile',
    'termios',
    'text_unidecode',
    'textwrap',
    'this',
    'thread',
    'threading',
    'timeit',
    'token',
    'tokenize',
    'tqdm',
    'trace',
    'traceback',
    'tracemalloc',
    'traitlets',
    'tty',
    'types',
    'typing',
    'typing_extensions',
    'tzdata',
    'unicodedata',
    'unittest',
    'uno',
    'unohelper',
    'unoserver',
    'urllib',
    'urllib.error',
    'urllib.parse',
    'urllib.request',
    'urllib.response',
    'urllib.robotparser',
    'urllib3',
    'uu',
    'uuid',
    'venv',
    'wadllib',
    'warnings',
    'wave',
    'wcwidth',
    'weakref',
    'webbrowser',
    'wheel',
    'wsgiref',
    'xdrlib',
    'xlrd',
    'xlsxwriter',
    'xml',
    'xml.dom',
    'xml.dom.minidom',
    'xml.dom.pulldom',
    'xml.etree.ElementTree',
    'xml.etree.cElementTree',
    'xml.parsers.expat',
    'xml.sax',
    'xml.sax.handler',
    'xml.sax.saxutils',
    'xml.sax.xmlreader',
    'xmlrpc',
    'xxlimited',
    'xxlimited_35',
    'yaml',
    'zipapp',
    'zipfile',
    'zipp',
    'zlib',
    'zoneinfo',


    'paddle', 'paddle.fluid', 'paddleocr', 'paddle.vision',
    'cv2', 'numpy', 'PIL', 'imageio', 'skimage',
    'backend', 'backend.config', 'backend.main',
    'backend.bean', 'backend.bean.subtitle_area',
    'backend.tools', 'backend.tools.ocr', 'backend.tools.constant',
    'backend.tools.hardware_accelerator', 'backend.tools.paddle_model_config',
    'backend.tools.process_manager', 'backend.tools.subtitle_detect',
    'backend.tools.subtitle_ocr', 'backend.tools.reformat',
    'backend.tools.theme_listener', 'backend.tools.version_service',
    'backend.tools.subtitle_extractor_remote_call',
    'backend.tools.python_runner', 'backend.tools.concurrent',
    'backend.tools.concurrent.task', 'backend.tools.concurrent.task_manager',
    'backend.tools.concurrent.future',
    'backend.sushi', 'backend.sushi.sushi_main', 'backend.sushi.subs',
    'ui', 'ui.home_interface', 'ui.setting_interface',
    'ui.advanced_setting_interface', 'ui.timeline_sync_interface',
    'ui.component', 'ui.component.video_display_component',
    'ui.component.task_list_component',
    'ui.icon', 'ui.icon.my_fluent_icon',
    'qfluentwidgets', 'qframelesswindow', 'qframelesswindow.utils',
    'darkdetect', 'chardet',
    'pydantic', 'pydantic_core', 'pydantic.v1', 'pydantic.version',
    'yaml', 'requests', 'tqdm', 'loguru', 'shapely', 'pyclipper',
    'pysrt', 'wordsegment', 'lmdb',
    'je_showinfilemanager', 'imageio_ffmpeg', 'Levenshtein',
    'PyQt5', 'PyQt5.QtCore', 'PyQt5.QtWidgets', 'PyQt5.QtGui', 'PyQt5.QtNetwork',
] + paddle_hidden + paddleocr_hidden + pyqt5_hidden + qfw_hidden + pydantic_hidden + pydanticcore_hidden
    + qframe_hidden + pytz_hidden + darkdetect_hidden + imageio_ff_hidden)

a = Analysis(
    [os.path.join(PROJECT_ROOT, 'gui.py')],
    pathex=[PROJECT_ROOT],
    binaries=all_binaries,
    datas=all_datas,
    hiddenimports=all_hidden,
    hookspath=[],
    runtime_hooks=[os.path.join(PROJECT_ROOT, 'hook-runtime.py')],
    excludes=[
        # Large third-party (safe to exclude)
        'matplotlib', 'scipy', 'IPython', 'jupyter', 'notebook',
        'pytest', 'sphinx', 'selenium',
        'modelscope', 'transformers', 'fairseq', 'torch', 'torchvision',
        'tensorflow', 'onnx', 'onnxruntime',
        'html5lib', 'bleach', 'webencodings', 'bs4',
        'tiff', 'tifffile',
        'sklearn', 'scikit_learn',
        # PySide6 remnants
        'PySide6', 'PySide6.QtCore', 'PySide6.QtWidgets', 'PySide6.QtGui',
        'PySideSix_Frameless_Window',
        # Unused PaddlePaddle modules
        'paddle.vision.models', 'paddle.text', 'paddle.audio',
        'paddle.quantization', 'paddle.sparse',
        'paddle.fluid.contrib', 'paddle.fluid.layers',
        'paddle.distributed', 'paddle.incubate', 'paddle.hapi',
        'paddle.fluid.transpiler', 'paddle.fluid.io',
        'paddle.optimizer', 'paddle.nn.quantization',
        'paddle.incubate.autograd',
    ],
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='VideoSubtitleExtractor',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=False,
    icon=os.path.join(PROJECT_ROOT, 'design', 'vse.ico'),
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=False,
    name='VideoSubtitleExtractor',
)
